### ISSUE TITLE
Buzzer won't work on Mamba F405 Mk2 (FURYF4OSD) FC.

### ISSUE THREAD

**Issue by Tonsuke201450** [FlightOne/FalcoX-Issue-Tracker#103]
Version
10.1.0.5196

Target
FURYF4OSD (Mamba F405 Mk2 FC)

Describe the bug
Buzzer won't beep despite it is correctly installed hardware wise and setup with OSD.

To Reproduce

Solder a buzzer accordingly.
Setup buzzer switch in OSD.
No beep.

**Comment by dustyprops** [comment]
I'm facing the same issue. Everything wired correctly (Buz+ & Buz-). 2 wire buzzer does not beep.

**Comment by PGIII** [comment]
Try Version 10.1.0.5252 |10.1 Alpha 15| and see if you still have the issue

**Comment by dustyprops** [comment]
> Try Version 10.1.0.5252 |10.1 Alpha 15| and see if you still have the issue

Okay will do. Thanks!

**Comment by dustyprops** [comment]
> Try Version 10.1.0.5252 |10.1 Alpha 15| and see if you still have the issue

Buzzer working now with alpha .5252, great job!

**Comment by Tonsuke201450** [comment]
I confirmed it's fixed.  Thanks for your work !
