### ISSUE TITLE
[FEATURE] New Target Request: BLADE_F7_HD

### ISSUE THREAD

**Issue by dustyprops** [FlightOne/FalcoX-Issue-Tracker#107]
Add new board target : BLADE_F7 & BLADE_F7_HD

**Comment by PGIII** [comment]
There’s already a request for the blade F7 is the HD version actually a different target ?

**Comment by dustyprops** [comment]
> There’s already a request for the blade F7 is the HD version actually a different target ?

HD version is another different target (BLADE_F7_HD)

**Comment by WilidWilly** [comment]
The HD target should work with the current Blade F7 firmware that is in the alpha already
