### ISSUE TITLE
[ISSUE] Foxeer F722 V2 ,DJI OSD problem

### ISSUE THREAD

**Issue by NikooFPV** [FlightOne/FalcoX-Issue-Tracker#113]
**Version**
10.1.0.5231

**Target**
Foxeer F722 V2

**Describe the bug**
OSD on DJI GOGGLES via VISTA doesnt work i dont even see voltage. Every pads are connected correctly, on betaflight all works.

**To Reproduce**
1. Flash Foxeer F722 V2 target
2. Set Uart 5 as MSP
3. No OSD

**Expected behavior**
Working OSD

**Additional context**
Hope you guys repair it.

**Comment by dustyprops** [comment]
> **Version**
> 10.1.0.5231
> 
> **Target**
> Foxeer F722 V2
> 
> **Describe the bug**
> OSD on DJI GOGGLES via VISTA doesnt work i dont even see voltage. Every pads are connected correctly, on betaflight all works.
> 
> **To Reproduce**
> 
> 1. Flash Foxeer F722 V2 target
> 2. Set Uart 5 as MSP
> 3. No OSD
> 
> **Expected behavior**
> Working OSD
> 
> **Additional context**
> Hope you guys repair it.

Did you try other uarts? I believe it needs to be on "usart" instead of "uart" in the peripherals page. That worked for me before.
