### ISSUE TITLE
AIKONF4 osd is not work

### ISSUE THREAD

**Issue by DHFPV** [FlightOne/FalcoX-Issue-Tracker#120]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by WilidWilly** [comment]
[FLX_AIKONF4_10.1.0.5255.zip](https://github.com/FlightOne/FalcoX-Issue-Tracker/files/5899109/FLX_AIKONF4_10.1.0.5255.zip)
Try manually flashing this file and see if it works now
