### ISSUE TITLE
MatekF411 1S Board, Dshot600 not working.

### ISSUE THREAD

**Issue by FiShJaeGeR** [FlightOne/FalcoX-Issue-Tracker#13]
Version 10.0.6.2818 Beta 6 Patch 3

1S Betafpv board Matekf411.
JESC 48Khz ESC firmware.
Setup works, with DShot300 motors spin and flying possible.
Setting to Dshot600 -> Motors do not spin when arming.

**Comment by PGIII** [comment]
I would Just use Dshot300 anyhow since its only 8khz, and in general dshot300 seems to be more compatible with BLheli_s as well

**Comment by gretel** [comment]
same issue for me on `mambaf411` - dshot600 was working fine on emuflight.

**Comment by gretel** [comment]
ah. changelog for `Verison 10.0.6.3373 Beta 6 Patch 9` reads:

```
Anyone using Dshot600 should now use Dshot8, anyone using Dshot8 should still use Dshot8
```

which does the trick for me.
