### ISSUE TITLE
TalonF7v2 Freezing at VTX setup

### ISSUE THREAD

**Issue by lemoncfpv** [FlightOne/FalcoX-Issue-Tracker#134]
**Version**
Version 10.1.0.5252 |10.1 Alpha 15|

**Target**
talonF7v2

**Describe the bug**
cannot discover vtx or advance past setup search for vtx.  Also OSD display still not working, virtual osd displays vtx search as noted.

**To Reproduce**
will not do osd setup via lipo plug in, or in the configurator virtual osd.

**Expected behavior**
need to get the target running!

**Screenshots**

**Additional context**
a few other issues were addressed and resolved (pitmode 5v cuttoff) via facebook messenger testing group, :D

**Comment by makaluch** [comment]
I'm also experiencing this. Setup freezes at VTX smartaudio detection, then the FC restarts.

Setup:
Talon V2 MPU6000 FC
Talon Gigawatt ESC (Aikon w/ heatsink)
TBS Unify Pro32 Nano - SA on UART4 (moved from tx1 to tx4) 5v pad jumped
XM+ - UART3

-Screenshot attached.
![FL1-setup-issues-1](https://user-images.githubusercontent.com/79026016/107863732-83cedd00-6e0b-11eb-8e61-cc88d263b5fe.jpg)

-Debug Info:
bundle.js:1 Error: Get Version Error: timeout in Access Mutex
    at bundle.js:1
    at tryCatch (C:\Users\mark\AppData\Local\Programs\FalcoX Configurator Alpha\resources\app.asar\node_modules\regenerator-runtime\runtime.js:63)
    at Generator.invoke [as _invoke] (C:\Users\mark\AppData\Local\Programs\FalcoX Configurator Alpha\resources\app.asar\node_modules\regenerator-runtime\runtime.js:293)
    at Generator.throw (C:\Users\mark\AppData\Local\Programs\FalcoX Configurator Alpha\resources\app.asar\node_modules\regenerator-runtime\runtime.js:118)
    at ur (bundle.js:1)
    at c (bundle.js:1)
(anonymous) @ bundle.js:1
tryCatch @ C:\Users\mark\AppData\Local\Programs\FalcoX Configurator Alpha\resources\app.asar\node_modules\regenerator-runtime\runtime.js:63
invoke @ C:\Users\mark\AppData\Local\Programs\FalcoX Configurator Alpha\resources\app.asar\node_modules\regenerator-runtime\runtime.js:293
(anonymous) @ C:\Users\mark\AppData\Local\Programs\FalcoX Configurator Alpha\resources\app.asar\node_modules\regenerator-runtime\runtime.js:118
Tr @ bundle.js:1
c @ bundle.js:1
Promise.then (async)
Tr @ bundle.js:1
a @ bundle.js:1
Promise.then (async)
Tr @ bundle.js:1
a @ bundle.js:1
(anonymous) @ bundle.js:1
(anonymous) @ bundle.js:1
(anonymous) @ bundle.js:1
(anonymous) @ bundle.js:1
tryCatch @ C:\Users\mark\AppData\Local\Programs\FalcoX Configurator Alpha\resources\app.asar\node_modules\regenerator-runtime\runtime.js:63
invoke @ C:\Users\mark\AppData\Local\Programs\FalcoX Configurator Alpha\resources\app.asar\node_modules\regenerator-runtime\runtime.js:293
(anonymous) @ C:\Users\mark\AppData\Local\Programs\FalcoX Configurator Alpha\resources\app.asar\node_modules\regenerator-runtime\runtime.js:118
Tr @ bundle.js:1
a @ bundle.js:1
Promise.then (async)
Tr @ bundle.js:1
a @ bundle.js:1
(anonymous) @ bundle.js:1
(anonymous) @ bundle.js:1
(anonymous) @ bundle.js:1
e @ bundle.js:1
setTimeout (async)
(anonymous) @ bundle.js:1
Promise.then (async)
e @ bundle.js:1
setTimeout (async)
(anonymous) @ bundle.js:1
Promise.then (async)
e @ bundle.js:1
setTimeout (async)
(anonymous) @ bundle.js:1
Promise.then (async)
e @ bundle.js:1
setTimeout (async)
(anonymous) @ bundle.js:1
Promise.then (async)
e @ bundle.js:1
setTimeout (async)
(anonymous) @ bundle.js:1
Promise.then (async)
e @ bundle.js:1
setTimeout (async)
(anonymous) @ bundle.js:1
Promise.then (async)
e @ bundle.js:1
setTimeout (async)
(anonymous) @ bundle.js:1
Promise.then (async)
e @ bundle.js:1
setTimeout (async)
(anonymous) @ bundle.js:1
Promise.then (async)
e @ bundle.js:1
setTimeout (async)
(anonymous) @ bundle.js:1
Promise.then (async)
e @ bundle.js:1
setTimeout (async)
(anonymous) @ bundle.js:1
Promise.then (async)
e @ bundle.js:1
setTimeout (async)
(anonymous) @ bundle.js:1
Promise.then (async)
e @ bundle.js:1
setTimeout (async)
(anonymous) @ bundle.js:1
Promise.then (async)
e @ bundle.js:1
setTimeout (async)
(anonymous) @ bundle.js:1
Promise.then (async)
e @ bundle.js:1
setTimeout (async)
(anonymous) @ bundle.js:1
Promise.then (async)
e @ bundle.js:1
setTimeout (async)
(anonymous) @ bundle.js:1
bundle.js:1 Error: Serial Promise Write Timeout When Writing: OSDOFF
OSDOFF
 Got: 
    at f (bundle.js:1)
