### ISSUE TITLE
HAKRC MINI DJI Stack F7 (MATEKF722SE ) no onboard memory (dataflash) detected

### ISSUE THREAD

**Issue by N4V1G4T0R** [FlightOne/FalcoX-Issue-Tracker#140]
Bug: On the 20x20mm HAKRC MINI DJI Stack F7 the Onboard Ram is not detected (MATEKF722SE is factory default firmware)

This is just a configuration issue. Following CLI Parameters will fix that:
resource SDCARD_CS 1 NONE
resource FLASH_CS 1 D02
set blackbox_device = SPIFLASH
set flash_spi_bus = 3

I already contacted the supplier to fix that, but until then you'll have to fix that manually.

**Comment by PGIII** [comment]
The MatekF722SE target isn’t supported yet and there’s no support for external flashes for logging atm so not sure how this issue is relevant

**Comment by N4V1G4T0R** [comment]
Sorry, wrong channel.
