### ISSUE TITLE
Won't save config 

### ISSUE THREAD

**Issue by ajp1078** [FlightOne/FalcoX-Issue-Tracker#142]
**Describe the bug**
Runs through all wizards fine. Motors correct direction lay flat, on nose set up finishes says to reboot power cycle. 
Do so..... No change in Configurator screen and then wizards start again. I repeated this a few times still no saving of setup. 
Spoke to Nick Willard and tried the following.
RESETCONFIG
SAVE
msg #rest OK
Wizards launched again 
Did set up again
Before power cycle went into terminal and did following
SET wizard_flag=127
#ok
save
It bypassed the wizards I had the OSD screen up but would not arm or respond to switches on transmitter.
Tried that same process again SET wizard_flag=127
 got the following msg
#ok 
Then when I tried to 
save I got
#error save failed
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
MAC OSX 
Chrome latest version

**Additional context**

**Comment by PGIII** [comment]
What FC is this and what does the error message show when you save ?

**Comment by ajp1078** [comment]
Hey mate,

It is the lightning H7 when I hit save it says
#error save failed

First time I tried bypassing the wizards it did but wouldn't arm so
tried again a few times and kept getting the
#error save failed message

Thanks

**Comment by PGIII** [comment]
Can you get a video of what youre doing when you see that message

**Comment by ajp1078** [comment]
Hi Preston,

Yep I will get that through to you.

Cheers

**Comment by proggod** [comment]
No updates so closing

**Comment by ajp1078** [comment]
I still haven't solved the issue. I have just had no time to get a good
video of the issue yet. So I will endeavour to get it to you asap

Regards
