### ISSUE TITLE
[NEW TARGET] New Target For Firmware

### ISSUE THREAD

**Issue by carlonz87** [FlightOne/FalcoX-Issue-Tracker#149]
Hi, anybody interested in kakute target? F7 mini for me, but have a few f4 laying around so a target for every kakute would be perfect!

**Comment by GiulianoDeMicheli** [comment]
I am also interested in having a target for this flight controller

**Comment by PGIII** [comment]
If theres multiple targets for them please open a issue for each and make sure to put the target names in the title

**Comment by PGIII** [comment]
Looks like there’s a request for the F4 #118 and the F7 #139 now so closing this issue
