### ISSUE TITLE
The backup function does not work

### ISSUE THREAD

**Issue by FerrisFPV** [FlightOne/FalcoX-Issue-Tracker#15]
After clicking backup, the loading message is still displayed and the file selection window does not open.

**Comment by PGIII** [comment]
Should be fixed in 2.0.1, please try that and let me know if you still have issues

**Comment by FerrisFPV** [comment]
Unfortunately it doesn't work - message:
"Loading...
This is taking way to long, try reconnecting your FC"
I try to reconnect FC but it doesn't work either.

**Comment by noahwaldner** [comment]
@FerrisFPV wich firmware version are you on?

**Comment by FerrisFPV** [comment]
10.0.6.2823 Alpha
