### ISSUE TITLE
Talon F7V2 target only motor 4 arms 

### ISSUE THREAD

**Issue by origdragon** [FlightOne/FalcoX-Issue-Tracker#154]
**Version**
10.1.0.5334

**Target**
TalonF7V2

**Describe the bug**
All motors have first set of tones only motor 4 has second set of tones. Only motor 4 arms

**To Reproduce**
1. Plug in battery 
2. Arm

**Expected behavior**
Motors arm

**Comment by makaluch** [comment]
I can confirm I'm having the same issue:

Talon F7 V2 FC
Talon Gagawatt V2 esc - Aikon v32.7

- Only motor 4 works.
- Blheli pass-thru only sees ESC#4 - " connect > read setup "
![FL1_esc_issue1](https://user-images.githubusercontent.com/79026016/108459489-9e4def80-722b-11eb-8da7-9631e64b4315.jpg)
-Blheli finds all 4 when you click "check"
![FL1_esc_issue2](https://user-images.githubusercontent.com/79026016/108459545-b9206400-722b-11eb-9474-7cf0ccc27e00.jpg)
After finding all 4, unable to test motors in blheli
![FL1_esc_issue3](https://user-images.githubusercontent.com/79026016/108459587-c9d0da00-722b-11eb-912d-401bcd30e534.jpg)

Dshot 16 - no change
Dshot 600 - no change
Verified latest Blheli version, confirmed hexs
