### ISSUE TITLE
FW Version 10.1.0.5334 won't arm 98% of the time

### ISSUE THREAD

**Issue by josuefpv** [FlightOne/FalcoX-Issue-Tracker#160]
**Version**
FW Version 10.1.0.5334 Bug

**Target**
H7 flight controller

**Describe the bug**
When using Version 10.1.0.5334, the esc's will not complete boot-up tones and thus isn't syncing to FC correctly. This results in not being able to get motors spinning of course. If I un-plug the quad 15 times, it may finally boot up correctly and allow for motors to spin 1 out of the 15 times kind of like playing Russian roulette. Definitely a FW bug because then when I go back to FW 10.1.0.4984, this issues goes away completely and the esc is able to sync with the FC 100% of the time.

**Comment by PGIII** [comment]
10.1 Alpha 18 should fix this issue
