### ISSUE TITLE
[ NEW TARGET] Furiousfpv racepit mini f4

### ISSUE THREAD

**Issue by sniperxnl** [FlightOne/FalcoX-Issue-Tracker#166]
Request target for Furiousfpv racepit mini f4

**Comment by sniperxnl** [comment]
Any idear when ready guys?

**Comment by PGIII** [comment]
> Any idear when ready guys?

Theres a lot of targets that have been requested and other things were working on as well, i cant give you an exact timeline but we will take a look at it, i believe the F7 version is already supported

**Comment by sniperxnl** [comment]
F7 is indeed supported, only my complete fleet and from others use a lot F4 minis, when do you think it is up?

**Comment by NelisFPV** [comment]
@PGIII any update on this target? Lots of people here in europe running this fc and want to try the falcoX license on them.

**Comment by PGIII** [comment]
Supported in alpha
