### ISSUE TITLE
FalcoX 2823 AmpDraw numbers updating to quick

### ISSUE THREAD

**Issue by enrico320i** [FlightOne/FalcoX-Issue-Tracker#17]
**Version**
2823

**Target**
Revolt

**Describe the bug**
I'm using the Afterburner ESC with current wire Setup to MillivoltOSD v2. In FalcoX osd "AmpDraw" is showing the Number very fast updating so that it can not be reading anytime. Number is Jumping up and down crazy fast. It's not an Big issue, but mabey it can be fixed. The "mah used" feature is working fine. Also it does the same on an other Quad with Furling32 ESC.

**To Reproduce**

**Expected behavior**
Mabey it can be fixed in some feature Version. It Looks to me like it Needs Filtering like the Voltage Display in OSD, this works fine too. Seams the Amp Draw is getting no Filtering and gets updated live all the time.

**Screenshots**
Powerplay DVR file can be downloaded here from my Google Drive.
https://drive.google.com/file/d/1Pk9LF3oH8ITNFdiNq2Zps2yVo7bW1UGC/view?usp=sharing

**Additional context**

**Comment by PGIII** [comment]
Weve been meaning to add a More filtered current draw reading for the OSD for a while ill have to take a look at it this week

**Comment by enrico320i** [comment]
Thanks man, it's not a big issue and there is truly important stuff. But I
use it from time to time to see how high the amp draw is on a new setup 👌

Greetings from Germany Enrico

Am 10. März 2020 05:51:15 schrieb PGIII <notifications@github.com>:

**Comment by PGIII** [comment]
Latest version have more filtering on amp draw and should fix this issue
