### ISSUE TITLE
[FEATURE] Disable long beep at startup

### ISSUE THREAD

**Issue by andytroy** [FlightOne/FalcoX-Issue-Tracker#172]
**Is your feature request related to a problem? Please describe.**
My Hellgate beeper, beeps for like 8 seconds at startup. During shoots this can be a problem, because they might be recording audio and it's really annoying. I need the buzzer because I'm flying in environments where I could lose the quad.

**Describe the solution you'd like**
Make this optional or disable it, like the old firmware.

https://youtu.be/_HV2LWt4tsg

**Comment by PGIII** [comment]
We can probably add an option to disable it in one of the next few alphas

**Comment by kennytakfpv** [comment]
This feature would be greatly appreciated. Could you, please, add the possibility to turn off the startup buzzer beeps?

**Comment by PGIII** [comment]
Startup Beep will be Disabled in the Next Alpha

**Comment by PGIII** [comment]
10.1 Alpha 29 has it disabled
