### ISSUE TITLE
Yaw twitches when mixing Yaw and Roll on Lightning H7

### ISSUE THREAD

**Issue by Georgeandrew7** [FlightOne/FalcoX-Issue-Tracker#175]
**Version**
10.1.0.5368

**Target**
Lightning H7 Wild Willy 

**Describe the bug**
Mixing yaw and roll together causes yaw twitches and yaw spins of death. 

**To Reproduce**

1. Attempt to fly 
2. Mix yaw and roll together going in the same direction. 
3. Try both directions 

**Expected behavior**
Reliable flight characteristics. 

Tried all tuning presets.

**Comment by PGIII** [comment]
That sounds like an ESC desync, what are your rates set to and what esc and esc settings are you using

**Comment by Georgeandrew7** [comment]
Esc settings: demag compensation high,
Timing 25 deg, frequency 24khz

**Comment by Georgeandrew7** [comment]
Rates: Vanover v2 preset

**Comment by PGIII** [comment]
I would try 32 or 48khz for Motor PWM

**Comment by Georgeandrew7** [comment]
Okay, thank you! I'll keep you posted on the results.
