### ISSUE TITLE
Motor 2 Not Spinning on MatekF722SE

### ISSUE THREAD

**Issue by achmiral** [FlightOne/FalcoX-Issue-Tracker#177]
**Version**
Version 10.1.0.5407 |10.1 Alpha 19|

**Target**
MatekF722SE

**Describe the bug**
Motor 2 not spinning, even when I reconfigured the wizard several times.

**To Reproduce**
1. Flash FalcoX 10.1.0.5407 to MatekF722SE
2. Plug the battery and start the wizard
3. Oh the motor idle wizard, the motor 2 is not spinning

**Expected behavior**
All the 4 motors spinning, I've tried to flash the FC with betaflight, all motors are spinning as the I expected.

**Screenshots**
https://youtu.be/8F37RFx5NxU

**Comment by WilidWilly** [comment]
[FLX_MATEKF722SE_10.1.0.5417.zip](https://github.com/FlightOne/FalcoX-Issue-Tracker/files/6134302/FLX_MATEKF722SE_10.1.0.5417.zip)
It appears the pin timer wasnt mapped right, give this fw a shot and it should work fine now

**Comment by achmiral** [comment]
Thank you @WilidWilly 👍

**Comment by WilidWilly** [comment]
@achmiral did that bin work?

**Comment by achmiral** [comment]
@WilidWilly yup, it is work, thank you 👍
