### ISSUE TITLE
[NEW TARGET] TBS Pod racer AIO (STM32F411) WITH GPS on soft serial ?

### ISSUE THREAD

**Issue by Enlightx** [FlightOne/FalcoX-Issue-Tracker#178]
TBS AIO board https://www.team-blacksheep.com/products/prod:tbs_podraceraio

GPS needs to be remapped to non uart outputs using soft serial not sure if thats possible with falco? (see tbs page above)

iv got one one on the way for a 7inch lightweight build so happy to test.

**Comment by PGIII** [comment]
Soft serial definitely isn’t super high priority, GPS is pretty data heavy I’m not sure soft serial would be a great solution for it, what does that board use the hardware UARTs for ?

**Comment by PGIII** [comment]
Should be supported now
