### ISSUE TITLE
[FEATURE] ExpressLRS doesnt support on furyF4OSD

### ISSUE THREAD

**Issue by ridwannurfalah** [FlightOne/FalcoX-Issue-Tracker#180]
r9m mini receiver using expresslrs was not detected.

**Comment by PGIII** [comment]
What protocol are you using ? and how do you have it connected

**Comment by ridwannurfalah** [comment]
i’m using EXpressLRS flashing via betaflightpassthrough method, everything going successfull flashing…. and connect (RX) via A1 to tx1 (FC) , A2 to RX (fc), gnd and (+)… but on Falcox alpha cannot find radio rx (still searching)until 10 minute

**Comment by ridwannurfalah** [comment]
> What protocol are you using ? and how do you have it connected

using crsf on tx... and connected the pin a1 &a2 on rx to FC

**Comment by PGIII** [comment]
so the protocol the receiver is outputting is CRSF ?

**Comment by ridwannurfalah** [comment]
> so the protocol the receiver is outputting is CRSF ?

flashing instructions r9mini / mm using CRSF https://github.com/ExpressLRS/ExpressLRS/wiki/OpenTX-and-Betaflight-Setup

**Comment by AlessandroAU** [comment]
Is serial passthrough supported on F1? @ridwannurfalah log of the console output when flashing is attempted would be helpful.

**Comment by ridwannurfalah** [comment]
> Is serial passthrough supported on F1? @ridwannurfalah log of the console output when flashing is attempted would be helpful.

this notification from log file, : data: '*** [upload] Exception : No valid serial port detected or port already open\n'
  },
  level: 'info',
  message: 'logs stream output'

**Comment by PGIII** [comment]
Theres no UART to USB Serial passthrough, are you trying to flash the Rx or are you having issues detecting ?
