### ISSUE TITLE
|10.1 Alpha 20| GPS Data Not Updating In CRSF Telem

### ISSUE THREAD

**Issue by David180680** [FlightOne/FalcoX-Issue-Tracker#182]
Target: Lightning

Crossfire Telemetry :
the values ​​of the gps coordinates are always at 0
the values ​​of the gps speed are always at 0
the value of altitude is different that once in the osd once the kwad is arming

**Comment by PGIII** [comment]
Are you sure the GPS is connected? do you see gps coordinates in the OSD ?

**Comment by David180680** [comment]
Yep i'm sure . and i see  gps  coordinate and speed gps in OSD

**Comment by PGIII** [comment]
Ill have to have @WilidWilly take a look he should have GPS hooked up, don't have one set up right now I can check with

**Comment by David180680** [comment]
Probleme solved with Alpha 21 , thanks Guys
