### ISSUE TITLE
|10.1 Alpha 20| with H7 GPS Wizard

### ISSUE THREAD

**Issue by David180680** [FlightOne/FalcoX-Issue-Tracker#183]
GPS Wizard Highest point:
there is a bug when i have to fly 5s , my quad turns on itself when I put the gas on

**Comment by PGIII** [comment]
Im not really sure what you mean and are you saying you're having this issue during the GPS wizard?

**Comment by David180680** [comment]
Yes I'm having this issue on the GPS Wizard

**Comment by PGIII** [comment]
But what exactly is happening your description isn't super clear, did you happen to get a DVR of the issue ?

**Comment by David180680** [comment]
see dvr on the comment of Preston Garrison : https://www.facebook.com/groups/flightone/permalink/4110452725673165/

**Comment by David180680** [comment]
problem solved by following advice from Wild Willy : " I think you may have to arm and hover the quad first though before running the RTH setup wizard to get the gyro and accelerometer data running right"
