### ISSUE TITLE
|10.1 Alpha 20| H7  : Blheli32 Telemtry

### ISSUE THREAD

**Issue by David180680** [FlightOne/FalcoX-Issue-Tracker#185]
Telemetry Blheli 32  tekko32 F3 conected to Pad telemtry of the H7
Telemetry Auto = ON in Blheli32

Impossible to detected Blheli32 telemetry in FalcoX

**Comment by PGIII** [comment]
I think Auto sends telemetry on its own, that's only for when you're using multishot

**Comment by David180680** [comment]
So if i use Dshot32 
what should i do to retrieve the info?  ( MaH used )

**Comment by David180680** [comment]
?

**Comment by PGIII** [comment]
You dont want auto telem enabled in the ESC
