### ISSUE TITLE
Not able to change pilot name from FlightOne

### ISSUE THREAD

**Issue by Georgeandrew7** [FlightOne/FalcoX-Issue-Tracker#186]
**Describe the bug**
When attempting to save any other pilot name except for FlightOne, I get error saving code: 30002

Version: 10.1.0.5414 Alpha 20

**To Reproduce**
1. Go to the OSD menu
2. Set wanted pilot name 
3. Save 
4. See error 30002

**Expected behavior**
Saving of pilot name and seeing it in the OSD.

**Comment by PGIII** [comment]
Will see if I can replicate it, what did you set the pilot name to ?

**Comment by Georgeandrew7** [comment]
I tried every given name I could think of, even the name of the quad. Nothing but FlightOne would save properly. I believe I tried twenty or so different names and character combinations to see if it would save anything but FlightOne. The most prominent one I attempted was Switchback1.

**Comment by 2dogrc** [comment]
@PGIII This also does not work in the configurator on the PC.  Have to use the Terminal.
