### ISSUE TITLE
Version 10.1.0.5490 |10.1 Alpha 27|| Matek F722-SE. The Wizard doesn't detect RC-receiver 

### ISSUE THREAD

**Issue by viktor-k99** [FlightOne/FalcoX-Issue-Tracker#190]
**Version**
Version 10.1.0.5407 |10.1 Alpha 19|
....
Version 10.1.0.5470 |10.1 Alpha 25|
Version 10.1.0.5480 |10.1 Alpha 26|

**Target**
MatekF722SE (Flight Controller board- Matek F722-SE)

**RC**
TBS nano RX version 3.78
TBS nano RX version 4.10
TBS nano RX version 4.11
FrSky R-XSR (SBUS) firmware version 2.1.0

**Describe the bug**
After plug in the battery the wizard not found the VTX and start search RC-receiver. 
The search for RC-receiver continues endlessly

**To Reproduce**
**Steps to reproduce the behavior:**
Solded TBS nanorRX (rev. XFnano 45) on UART1 (or UART2, UART3, UART4)
Version 10.1.0.5467 |10.1 Alpha 24| to Matek F722SE
Plug in the lipo
Wait for the Wizard to start searching for the RC receiver.

**Expected behavior**
After plug in the battery the wizard should detect the RX.

**Screenshots**
https://youtu.be/OU81sKkArKo

**Comment by dieselshroom** [comment]
Just had this exact same issue when trying to run the wizard on this board. Had no choice but to go back to BF.

**Comment by PGIII** [comment]
What Speed is the crossfire set to and does it detect if you set the crossfire to ni sbus ?

**Comment by viktor-k99** [comment]
My settings Crossfire Micro TX
Multibind -    Enable
Region -        Open
Max Power - 100mW
Dyn.Power -  On
Frequency -  868 Mhz
Op. Mode  -  Normal

Settings Nano RX
Mode - 8 Ch
Telemetry - On
RF Profile - Dynamic
Failsafe Mode - Cut
RC by MAVLink - oh
RX Batt Sensor - OFF
RX Output map:
Output 1 - CRSF TX
Output 2 - CRSF RX

I set the following options:
- RF Profile - 150 Hz, Mode 8 ch
- RF Profile - 150 Hz, Mode 12 ch
- RF Profile - 50 Hz, Mode 8 ch
- RF Profile - 50 Hz, Mode 12 ch
- RF Profile - Dynamic, Mode 8 ch
- RF Profile - Dynamic, Mode 12 ch
 The wizard doesn't  detect the RC receiver Crossfire nano RX.
I set Output 1  at n.i.SBUS. The wizard didn't  detect the RC receiver Crossfire nano RX.
I reset my Crossfire Micro Tx and Nanor Rx to factory settings . The wizard doesn't  detect the RC receiver Crossfire nano RX again.

**Comment by yyacoel** [comment]
Same issue for me. with xfire nano.
Tried to use different UARTs (1/2/3), same behaviour.

**Comment by viktor-k99** [comment]
I think that the support team needs to test the firmware on the Matek board. Only after tests can the this issue be resolved.

**Comment by ojwright845** [comment]
Same issue with matek f722se. Frsky receiver not detected. Attempted manual configuration but no luck

**Comment by GFRaw** [comment]
Also stuck with unable to detect the RX, crsf nano.  Going back to BF for now.

**Comment by 3D-pilot** [comment]
As per viktor-k99 Matek F722SE Unable to detect TBS Nano Rx. Configurator keeps continuously cycling through RX options and unable to detect. Tried RESETCONFIG and various Uarts.

**Comment by PGIII** [comment]
[GYRO_FIX_IFLIGHTF722_TWING_10.1.1.5703.flx.zip](https://github.com/FlightOne/FalcoX-Issue-Tracker/files/6986810/GYRO_FIX_IFLIGHTF722_TWING_10.1.1.5703.flx.zip)
try this and see if it fixes it
