### ISSUE TITLE
[FEATURE] On DJI OSD set RSSI element red when value is less than X%

### ISSUE THREAD

**Issue by felipeng** [FlightOne/FalcoX-Issue-Tracker#194]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
On DJI OSD: when the RSSI (LQ) is less than X% (configurable) set the OSD element in red

**Describe alternatives you've considered**
Warning Alert

**Additional context**
N/A

**Comment by PGIII** [comment]
We don’t have any control over text color this is something DJI would have to implement
