### ISSUE TITLE
On DJI OSD the element "Arm Status" only shows "DISARMED"

### ISSUE THREAD

**Issue by felipeng** [FlightOne/FalcoX-Issue-Tracker#195]
**Version**
* FalcoX: 10.0.18.4939
* Vista: V01.00.0600
* Goggles: V01.00.0606

**Target**
RevoltOSD

**Describe the bug**
"Arm Status" element on DJI OSD only shows "DISARMED" or nothing when I arm

**To Reproduce**
1. Power on kwad/radio/goggles
1. Kwad disarmed (element: DISARMED)
1. Arm the kuad (element: disappear)
1. On Quopa mode (element: disappear)

**Expected behavior**
It should show others status, like:
* Quopa Armed
* First Arm
* 2ndDisarm
* Armed
But only shows DISARMED or nothing

**Screenshots**
N/A

**Additional context**
N/A

**Comment by PGIII** [comment]
We don’t have control over what that displays, I believe showing disarmed or nothing is normal for DJI
