### ISSUE TITLE
[FEATURE] Enable "time related elements" on DJI OSD

### ISSUE THREAD

**Issue by felipeng** [FlightOne/FalcoX-Issue-Tracker#197]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Enable these elements on DJI OSD:
* ArmTime C
* Arm Time
* Fly Time
* Time On

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by PGIII** [comment]
This requires DJI to add we have no direct control over the text
