### ISSUE TITLE
[NEW TARGET] New Target For Firmware CLRACINGF4

### ISSUE THREAD

**Issue by IntroFPV** [FlightOne/FalcoX-Issue-Tracker#199]

**Comment by Modrans** [comment]
I don't know if bumping this request gets any attention, but I'll happily Venmo $30 for a working CLRACINGF4 FalcoX firmware! I'm specifically looking for the JBF4, but it uses a CLRACINGF4 target in BF. 

Is there any information I can provide to assist?

**Comment by PGIII** [comment]
Now supported
