### ISSUE TITLE
Configure OSD is unreachable

### ISSUE THREAD

**Issue by ElMute** [FlightOne/FalcoX-Issue-Tracker#2]
can't access to this tab, stuck on "loading"

**Comment by DaSeppoFPV** [comment]
same here, seems like nothing is working right now

**Comment by noahwaldner** [comment]
I just fixed a bug wich might have casued this, what setups are you running?

**Comment by ElMute** [comment]
MAC OSX 10,14,6 
Revolt OSD, megabolt extreme, DJI FPV

**Comment by noahwaldner** [comment]
I fixed this, 2.0.1 with a fix will be released today

**Comment by SkeemoFPV** [comment]
> I fixed this, 2.0.1 with a fix will be released today

@noahwaldner Did this get released anywhere ?

**Comment by PGIII** [comment]
Should be fixed in the latest version that just got put up let me know if it still persists

**Comment by ElMute** [comment]
same, all is ok with last FW and configurator 2,0,1

**Comment by enrenard** [comment]
Same here with MacOs
