### ISSUE TITLE
Numerous issues in Configurator 2.0.2

### ISSUE THREAD

**Issue by Hellfire82** [FlightOne/FalcoX-Issue-Tracker#20]
I am using the latest configurator V 2.0.2.
I am using the latest FalcoX alpha build - Revolt Version: 10.0.6.2823.

The following 4 issues have been identified so far:

![Backup](https://user-images.githubusercontent.com/61711435/76450251-5c82bb00-63c5-11ea-83e1-e3aa6ec7bb4c.jpg)

When you click on the 'backup' button, the loading dialog box appears and nothing else happens (see screenshot above). I have waited for a considerable amount of time just in case of a delay before restarting the configurator.

![Blank Terminal](https://user-images.githubusercontent.com/61711435/76450253-5db3e800-63c5-11ea-9efc-9597f96da066.jpg)

When you paste / type commands into the serial terminal, nothing appears in the actual window like it used to e.g. in order to feedback info if a 'get' command is used or to say OK if a 'set' or 'save' command is used (see screenshot above).

![Configure OSD](https://user-images.githubusercontent.com/61711435/76450258-5e4c7e80-63c5-11ea-9ac0-666f08441978.jpg)

When you click on the 'Configure OSD' button, the loading dialog box appears and nothing else happens (see screenshot above). I have waited for a considerable amount of time just in case of a delay before restarting the configurator.

![Reload   Force reload](https://user-images.githubusercontent.com/61711435/76450259-5ee51500-63c5-11ea-8082-c3b70362b068.jpg)

When the configurator is hanging / not responding and either the reload or force reload option is selected within the 'view' tab, the screen just goes white and nothing happens (see screenshot above). The configurator has to be shut down and restarted in order for it to function again.

O/S - Windows 8.1 (all latest patches installed)
Browser - Version 80.0.3987.132 (Official Build) (64-bit)

**Comment by gretel** [comment]
same issues for me. why closed?

**Comment by Hellfire82** [comment]
All these issues have been fixed in the latest alpha configurator which is currently in testing.
