### ISSUE TITLE
Voltage Cell type detecting incorrectly (detects 6S as 5S)

### ISSUE THREAD

**Issue by Enlightx** [FlightOne/FalcoX-Issue-Tracker#201]
**Version**
10.1.0.5467

**Target**
H7

**Describe the bug**
Battery is at 3.75V per cell when connecting falco things its a 5S (confirmed via element iv not added to make sure) never had this problem before on revolt osd

**To Reproduce**
plug in a half used lipo

**Expected behavior**
picks up as 5S and calculates per cell voltage incorrectly (4.47V per cell lol FIREEEE)

**Screenshots**

**Additional context**

**Comment by proggod** [comment]
This is normal only way to detect battery is based on voltage and your voltage is high enough to be a over charged 5s.
