### ISSUE TITLE
Spinning uncontrollably after crash on H7 

### ISSUE THREAD

**Issue by Georgeandrew7** [FlightOne/FalcoX-Issue-Tracker#202]
**Version**
10.1.0.5467 Alpha 23

**Target**
Lightning H7 WildWilly 

**Describe the bug**
Crashing into a gate, the quad spins uncontrollably and unable to recover with the spin fix. It keeps spinning in one direction, then the other, and eventually hits the ground unless disarming and rearming quickly to recover. 

**To Reproduce**
1. Fly 
2. Crash and see if it spins uncontrollably 

**Expected behavior**
Quad fights any external force, not causing it to spin uncontrollably.

**Comment by PGIII** [comment]
you can increase SpinFix Recovery to give the ESC more time to recover, is it showing that spin fix is activating ?

**Comment by Georgeandrew7** [comment]
Increased SpinFix recovery, it did show that it was activating in the status, but never fully recovers until I disarm and rearm the quad.

**Comment by PGIII** [comment]
What do you have it set to now ? you can increase it more also i would make sure the ESCs are set to demag high, do you have any DVR of it ?

**Comment by Georgeandrew7** [comment]
I have it set to 220ms and 170ms. I also have demag set to high, but still seems to occur frequently. I will get some DVR footage of it when able.

**Comment by PGIII** [comment]
likely just need to increase recovery time some more, you can also adjust the other settings to make it activate sooner, what motors and escs are you using ?

**Comment by Georgeandrew7** [comment]
I've increased it to 190 and 270. Spin fix now no longer activates even after resetting the config. The motors I am using are the Five33 Headsup 1960kv motors and the ESC is a Hobbywing Xrotor 40A 4in1 Blheli32 ESC.

**Comment by PGIII** [comment]
What number are you increasing ? recovery affects how long it stays active for,  SpinFix Time To Enable changes how long it has to see high error before it enables Spin Fix, and SpinFix Max Error sets the threshold for what high error is. So if youre having issues with it activating you should decrease SpinFix Max Error or SpinFix Time To Enable

**Comment by jokker87** [comment]
Same problem on a HGLRCF722 target. Why is this even needed? BF just recovers from a crash.
