### ISSUE TITLE
Airbot F7 HDV stuck in wizard

### ISSUE THREAD

**Issue by diankurus** [FlightOne/FalcoX-Issue-Tracker#205]
**Version**
Version 10.1.0.5467

**Target**
AirbotF7HDV

Gyro: ICM20602

**Describe the bug**
Cant pass the fc direction setup. When quad is laying flat and roll left. It said ACC Z 0

**Expected behavior**
It passed the wizard

**Screenshots**
![image](https://user-images.githubusercontent.com/77162794/113962799-976a5300-9852-11eb-9110-70c33fe242c9.jpeg)

**Comment by PGIII** [comment]
Dont think anyones tested this target yet, does it show the right target when it connects that screen shot is pretty low res its hard to tell

**Comment by diankurus** [comment]
![image](https://user-images.githubusercontent.com/77162794/114640932-4bf4f080-9cfb-11eb-930f-a96f43200bac.jpeg)

Here the higher resolution. Error on wizard
