### ISSUE TITLE
FPV Google OSD unreadable 

### ISSUE THREAD

**Issue by Darkslide40** [FlightOne/FalcoX-Issue-Tracker#213]
flightone configurator Alpha
flight controller version  10.1.0.5480

target : MambaF7

on MAC OSD is good but on FPV googles, OSD unreadable.
See attached
![OSD Flightone](https://user-images.githubusercontent.com/82654767/115020546-07b04e80-9ebb-11eb-84d7-c28a74c33426.jpg)

**Comment by PGIII** [comment]
You just need to go in the osd menu and pick upload font

**Comment by Darkslide40** [comment]
thank you very much, it works!
