### ISSUE TITLE
switch 3 position not detected

### ISSUE THREAD

**Issue by Darkslide40** [FlightOne/FalcoX-Issue-Tracker#214]
Version 10.0.5480

Target : Mambaf7

I have a Jumper T-Lite and R-XSR, Switch 2 position work fine but Switch 3 position no detected, cannot assign functions on SWA and SWB switch.
same switch work well in betaflight.
Can you help me?

**Comment by Darkslide40** [comment]
after several tests, the chanel 8 is not detected.
I passed the 3-position switch on the chanel 9 and it works.

**Comment by PGIII** [comment]
Channel 8 is reserved for RSSI right now
