### ISSUE TITLE
iFlight Succex-e F4

### ISSUE THREAD

**Issue by Georgeandrew7** [FlightOne/FalcoX-Issue-Tracker#218]
HW: 
MCU：STM32F405

- Gyro：MPU6000

- Betaflight OSD：IFLIGHT OSD （AT7456E)

- Blackbox：16MB(W25Q128)

- Baro: BMP280(I2C）

Uarts: 
Uart 1: Configuration/MSP 

Uart 2: Free

Uart 4: For RX (Plug) 

Uart 6: BlHeli Telemetry 

Firmware target : BETAFLIGHTF4

**Comment by jokker87** [comment]
Already supported: https://flightone.com/firmware/alpha/FLX_BETAFLIGHTF4_10.1.0.5490.flx

**Comment by Georgeandrew7** [comment]
> Already supported: https://flightone.com/firmware/alpha/FLX_BETAFLIGHTF4_10.1.0.5490.flx

Ah, thank you!
