### ISSUE TITLE
[NEW TARGET] New Target For Firmware NewBeeDrone Infinity305

### ISSUE THREAD

**Issue by CoderElectronics** [FlightOne/FalcoX-Issue-Tracker#219]
This looks like a nice FC that is fit for FalcoX. Here is some info:

HW:

- MPU6000 Gyro
- STM32F405 CPUE @ 168mhz, can be overclocked
- Betaflight OSD
- No Blackbox chip by default, available seperately

UARTS:

- UART1 (INVERTER FOR SBUS)
- UART2 (FREE)
- UART3 (INVERTED TELEMETRY)
- UART4 (Free)
- UART5 (Smart Audio)
- UART6(Free)

Betaflight Target: NBD_INFINITYF4

**Comment by PGIII** [comment]
Supported in alpha
