### ISSUE TITLE
[NEW TARGET] New Target For Firmware APEX F7 HD FC

### ISSUE THREAD

**Issue by CoderElectronics** [FlightOne/FalcoX-Issue-Tracker#220]
This is a very unique stack that is one of my favorites, and it even has bluetooth!

Specs:
- STM32F722
- 16 MB of Flash
- USB-C
- Dual Gyro via SPI (MPU6000+ICM20602)
- Barometer BMP280 via I2C
- VTX Power Switch
- Cam Control
- Bluetooth Connectivity via Soldered Module (active, when board isn't armed)
- WS2812 LED Output
- Smart Audio/ Tramp
- Up to 6s Input

Betaflight Target: APEXF7

**Comment by PGIII** [comment]
Supported now
