### ISSUE TITLE
[NEW TARGET] New Target For Firmware TALON F7 FUSION

### ISSUE THREAD

**Issue by cross07705** [FlightOne/FalcoX-Issue-Tracker#224]
I found TALON F7 FUSION quite good for micro FPV drones. Could you help to add firmware for TALON F7 FUSION?
Thank you!

BF Target: TALONF7FUSION
HENA-TALONF7FUSION.config

SPECIFICATION
MCU: STM32F722RET6 216MHz
2x ICM20602 GYROS 90 deg phase
Built in Betaflight OSD
Up to 8S (36V) direct battery power
Buzzer pads for external buzzer
Built in voltage monitoring resistor
5V 2A BEC
Dedicated LDO for Gyro, noise free gyro power
Dedicated LDO for OSD, cleaner OSD signal
Led strip shares 5V with 5V/2A BEC
6 UARTS: UART1, UART2, UART3, UART4, UART5, UART6
Built in camera control pin with resistor and capacitor
5 Full UARTS with RX AND TX pins
Logical pin layout for cleanest build possible
8 pin 4 IN 1 ESC plug
Remapable LED pad for additional motor output
TX3, RX3 can be used for I2C for external compass
5V, VBAT selectable VTX and CAM power
16M Blackbox flash chip
No flicker VTX pit mode switch (positive switch)
M4 Can be selected either led_strip signal or M4 signal for RPM filtering

**Comment by PGIII** [comment]
Now supported
