### ISSUE TITLE
FC not detected after changing target  & flashing via alpha configurator

### ISSUE THREAD

**Issue by dustyprops** [FlightOne/FalcoX-Issue-Tracker#227]
Configurator - Alpha 10.1.8
FC - CrazyF411
Wrong flashed target - MATEKF411
Correct(changed) Target - MATEKF411RX

Only red LED lights up when usb connected.

**Comment by PGIII** [comment]
It sounds like you registered it as the wrong target. You can Change that in the configurator if you go to flashing then bootloader flashing and pick the change target button

**Comment by dustyprops** [comment]
Yes, I noticed this solution shortly after I sent this email. But after I
change the target, my board was not detected anymore. No blinking LED on
the FC, just solid LED.

**Comment by dustyprops** [comment]
Yes, I noticed this solution shortly after I submit this issue. But after I change the target, my board was not detected anymore. No blinking LED on the FC, just solid red LED.

**Comment by PGIII** [comment]
You can always flash in DFU mode what target did you change it to and what is it supposed to be ? also what is the serial number of the board
