### ISSUE TITLE
[NEW TARGET] New Target For Firmware Hobbywing F7 

### ISSUE THREAD

**Issue by BingQuanku** [FlightOne/FalcoX-Issue-Tracker#229]
Can the firmware of Hobbywing F7 FC be added in the near future?

**Comment by jimburroni** [comment]
Oh oui, ça serait super d'avoir cette cible pour moi aussi.

**Comment by LOFT330** [comment]
the correct Target on this fc is FLYWOOF7DUAL

**Comment by jimburroni** [comment]
> the correct Target on this fc is FLYWOOF7DUAL

Merci beaucoup !

**Comment by PGIII** [comment]
We'll Add it in the next round of targets

**Comment by BingQuanku** [comment]
> 我們將在下一輪目標中添加它

thanks

**Comment by PGIII** [comment]
Now supported
