### ISSUE TITLE
OSD CrossHair not aligned on Center DJI Goggles Tmotor F7 FC

### ISSUE THREAD

**Issue by Jurisjury** [FlightOne/FalcoX-Issue-Tracker#235]
**Describe the bug**
OSD Crosshair not aligned on center in DJI goggles 

**Expected behavior**
When using the Crosshair it should be at the center of the Screen Display

**Desktop (please complete the following information):**
Falco flashed on Tmotor F7 HD Flight Controller
Version 10.1.0.5503

**Additional context**

**Comment by PGIII** [comment]
This is a duplicate of #198
