### ISSUE TITLE
[NEW TARGET] New Target For JBF7_DJI FC

### ISSUE THREAD

**Issue by PanicoFPV** [FlightOne/FalcoX-Issue-Tracker#238]
JBF7_DJI FC.

**Comment by PGIII** [comment]
Now supported

**Comment by PanicoFPV** [comment]
You the man, thank you! 

Richard Panico

**Comment by PanicoFPV** [comment]
Good day- 

I just flashed my JBF7 DJI to Falco X (Config 10.1.8) and ran through the prompts just fine. Went to power cycle and now I’m NOT getting the ESC tones and getting “RX Lost” on home config page. Do you know how I can fix this? 

UART 1- CRSF
UART 2- DJI OSD
UART 3- NONE
UART 4- BLheli Telemetry (tried with and without) 
UART 5- NONE

Thank you all, 

Richard Panico
