### ISSUE TITLE
h7 reboots in flight for no reason, with firmware higher than 10.1.0.5186

### ISSUE THREAD

**Issue by michael9544** [FlightOne/FalcoX-Issue-Tracker#241]
h7 reboots in flight for no reason, with firmware higher than 10.1.0.5186

H7 + TBS Tracer

**Comment by PGIII** [comment]
Do you have a dvr of the issue and what fw version of tracer are you using

**Comment by michael9544** [comment]
No dvr, the fc reboots and the vtx is off. 
Tracer 5.07



Mit freundlichen Grüßen

Michael Falke



Tischlerei Falke
Molkereistrasse. 5
29393 Groß Oesingen

Fon:    05838 - 268
Mobil: 0171 - 1405386
Fax:    05838 - 1208
E-mail: ***@***.***

Diese E-mail wurde vom iPhone gesendet.

**Comment by PGIII** [comment]
There have been some recent changes to CRSF protocol in alpha 31 so try that and see if you still have the issue, try to get a dvr if possible

**Comment by michael9544** [comment]
The newest version works fine.
Thank you
