### ISSUE TITLE
Endpoints from Radioconfig are flawed since  10.1.1.5664 

### ISSUE THREAD

**Issue by michael9544** [FlightOne/FalcoX-Issue-Tracker#245]
H7

**Comment by PGIII** [comment]
I don’t really understand what this means what issue are you having?

**Comment by michael9544** [comment]
The endpoints Min + mid + maxrc,
the values ​​are not interpreted correctly.

**Comment by PGIII** [comment]
I don’t understand why do you think it’s not correct ? What issue are you having?

**Comment by michael9544** [comment]
I Look into Systeminfo.

Mid position on al channels by 2%
min and max have 100% by half stick movement.

**Comment by PGIII** [comment]
What Rx and radio are you using ?

**Comment by michael9544** [comment]
Tracer + Mambo

**Comment by PGIII** [comment]
What version is on Tracer also have you tried running RESET_WIZARD RADIO in the console and going through the radio setup again

**Comment by michael9544** [comment]
6.07

**Comment by PGIII** [comment]
Going through the Setup again fixes it for me, looks like its due to CRSFv3 having a higher resolution than before

**Comment by michael9544** [comment]
i try RESET_WIZARD RADIO.

in systeminfo:
sometimes value goes correct from-100 to +100
after reboot
sometimes goesfrom from -82 to +76

minrc=0
midrc=1022
maxrc=2047

**Comment by michael9544** [comment]
i have no problems with 10.1.0.5186

minrc=175
midrc=992
maxrc=1809

**Comment by PGIII** [comment]
Its due to CRSFs changing resolution ill have to look into normalizing all of them into the same range

**Comment by PGIII** [comment]
> i have no problems with 10.1.0.5186
> 
> minrc=175
> midrc=992
> maxrc=1809

that version doesn't support the dynamic resolution with CRSF v3 which is why

**Comment by PGIII** [comment]
[CRSF_Scaling_FixLIGHTNING_10.1.1.5667.flx.zip](https://github.com/FlightOne/FalcoX-Issue-Tracker/files/6933374/CRSF_Scaling_FixLIGHTNING_10.1.1.5667.flx.zip)
try this, you'll probably need to redo the radio wizard

**Comment by michael9544** [comment]
I have now flown 4packs.
no problems so far.
feels even better than 10.1.0.5186.
good job, thank you very much
