### ISSUE TITLE
Size font not  be selectable 

### ISSUE THREAD

**Issue by michael9544** [FlightOne/FalcoX-Issue-Tracker#246]
H7

all versions

**Comment by PGIII** [comment]
What fw version are you using this was recently fixed in alpha31

**Comment by michael9544** [comment]
Version 10.1.1.5664 |10.1 Alpha 31|

**Comment by PGIII** [comment]
Ill have to take a look

**Comment by PGIII** [comment]
[Charmap_Test_LIGHTNING_10.1.1.5667.flx.zip](https://github.com/FlightOne/FalcoX-Issue-Tracker/files/6932246/Charmap_Test_LIGHTNING_10.1.1.5667.flx.zip)
Try this should fix it

**Comment by michael9544** [comment]
yes, OSD is ok now
