### ISSUE TITLE
H7 Quopa and Motorbeep on same switch, quad freaking out

### ISSUE THREAD

**Issue by michael9544** [FlightOne/FalcoX-Issue-Tracker#247]
H7 
redux32

dshot 64

I have Quopa and Motorbeep on same switch,
When new arm, sometimes the motor direction is wrong and quad freaking out

**Comment by PGIII** [comment]
They Both send Commands to the motors, could maybe add a latching to the motor beep mode so it needs to be on for a period of time before sending the commands, what position on the switches is each mode on ?

**Comment by michael9544** [comment]
quopa and motorbeep are on the same switch position

**Comment by PGIII** [comment]
Ah well they can't be on the same position they both send commands to the ESCs so they wouldn't be able to do that at the same time

**Comment by michael9544** [comment]
is it possible on on switch ?

down - nothing
mid -launch + motor beep 
up- quopa
