### ISSUE TITLE
Matek F411 

### ISSUE THREAD

**Issue by michael9544** [FlightOne/FalcoX-Issue-Tracker#255]
.5717

When in OSD, and go to  save or save and exit, nothing happend, and the the FC reboots

Tracer + Mambo

**Comment by PGIII** [comment]
Can you get a dvr of it

**Comment by michael9544** [comment]
https://user-images.githubusercontent.com/65806700/130351556-1d077466-8c49-4a7c-ab1c-f59616cdbcf4.MOV

telemetry say " sensor lost", and after approx 30 sec. it reboot

**Comment by PGIII** [comment]
does save and exit do the same thing ?

**Comment by michael9544** [comment]
yes.
but the cam picture comes back
