### ISSUE TITLE
3 profiles tune not well restored

### ISSUE THREAD

**Issue by ElMute** [FlightOne/FalcoX-Issue-Tracker#26]
the 3 profile set up are not well saved and restored with configurator 2,02 and alpha 3065

edit the 3 setup, backup it, and try to restore it, only one of the 3 setup is well restored

**Comment by PGIII** [comment]
The configurator doesnt support the multiple updates yet that will come in its next update

**Comment by PGIII** [comment]
Closing since this is a duplicate of #43
