### ISSUE TITLE
[ALPHA] RevoltOSD OSD Flickering 

### ISSUE THREAD

**Issue by diankurus** [FlightOne/FalcoX-Issue-Tracker#261]
**Version**
10.1.1.5721

**Target**
Revolt Osd & FuryF4osd

**Describe the bug**
Osd bug. Flickering on menu and home screen / osd screen both revoltosd and furyf4osd

**Comment by diankurus** [comment]
I tried to flash to stable firmware to make sure its not hardware problem and yeah osd is good on stable version

**Comment by PGIII** [comment]
Do you have a video of the issue?

**Comment by diankurus** [comment]
I cant post video. Since flickering is match with video fps so in video wont be any osd flickering. In dvr its show no osd . But there're osd!

[Uploading 131506760...]

**Comment by diankurus** [comment]
Updates :

Osd works fine on caddx ratel

Osd flickering on runcam racer 3.

5v was feed from vtx before. Then 5v from fc .

**Comment by diankurus** [comment]
so it was solved.

My Runcam use NTSC as default. falcox video system in auto didnt work. 
my bad. i did try to change on falco video system to NTSC and hit save and exit without power cycle so make no difference

now tried to use pal on my runcam my osd is good
change runcam to ntsc and change falco video system to NTSC and hit save and do powercycle OSD is good

**Comment by PGIII** [comment]
Ah the OSD chip must just have issues detecting which mode that camera is on, glad you figured it out
