### ISSUE TITLE
Blheli_32 no connect.

### ISSUE THREAD

**Issue by MakeDa002** [FlightOne/FalcoX-Issue-Tracker#262]
**Version**
FalcoX version 10.1.0.5490

**Target**
Revolt

I can´t connect to Blheli_32, report an error with motor output. Attached image of the error. 
With the latest alpha version it works.

1. connect the batery.
2. connect the usb. 
3. open blheli_32 configurator and read setup.

**Screenshots**
there is a screenshots. https://drive.google.com/file/d/1Vy2w6x4aCkzfeMd6XLm0H_ixZ9hfTEOd/view?usp=sharing

**Comment by d00m303** [comment]
![blheli1111](https://user-images.githubusercontent.com/65198107/131913657-009c48aa-1459-4bba-9bd4-51da94f23915.JPG)

Select proper protocol ;)
