### ISSUE TITLE
Use 3 position switch.

### ISSUE THREAD

**Issue by MakeDa002** [FlightOne/FalcoX-Issue-Tracker#263]
I can't use the same switch for buzzer and quopa. For example, in middle position for buzzer and top position for quopa mode. I use to configuring this type of switch in beta in this mode but in falcox i can't. This feature improve the modes of falcox and we can use the more modes, now I have to use one switch for buzzer, other switch for quopa and other switch for vtx on.

Use the 3 position switch, it has 3 values, 1000, 1500 and 2000.

**Comment by PGIII** [comment]
You can definitely use all 3 pos on 3 position switches for different modes, what happens when you try ?
