### ISSUE TITLE
PID value is set to 49 for the different profile

### ISSUE THREAD

**Issue by ElMute** [FlightOne/FalcoX-Issue-Tracker#27]
- would be great to could select our custom set up in the 3 profiles available, at this time PID are set to 49 for all parameters when we select "custom"

- would be great if the changes made could stay in place when we switch between the profiles, need to save after each edit before switch between the profiles or edit is lost during the switch

**Comment by PGIII** [comment]
That just sounds like its not being set to defaults, we can fix that but try selecting the default preset and then edit a value and it will update the custom tune

**Comment by ElMute** [comment]
yup it updates the custom in the profile selected, but for exemple : 

on my profile 2, if i want test only small adjustements of my custom preset from profile 1, I need to re-edit all the preset because all is set to 49. 

would be great if we could recall our custom preset from profile 1 to the 2 others profile
