### ISSUE TITLE
[NEW TARGET] New Target For Firmware MATEK H7 SLIM

### ISSUE THREAD

**Issue by npotoc** [FlightOne/FalcoX-Issue-Tracker#273]
Hi!

would it be possible to create a target for Matek H7 slim?

Thx!

Niko

**Comment by PGIII** [comment]
Theres no plans to support 3rd party H7 boards at the moment ill reopen this issue if that changes

**Comment by npotoc** [comment]
Hi!

Can i exchange my order of 3 H7 for megabolt extremes or afterburners if you by chance have any left on the side?

Thx!

Niko
