### ISSUE TITLE
OSD over DisplayPort for SharkByte stopped working with latest SharkByte firmware version 20102021

### ISSUE THREAD

**Issue by Tigereye2k6** [FlightOne/FalcoX-Issue-Tracker#279]
**Version**
10.1.1.5792

**Target**
TMOTORF7

**Describe the bug**
The OSD stopped working with the latest SharkByte Firmware 20102021. I have flashed the latest FalcoX Firmware but it still wont work. With the previous SharkByte Firmware version all worked well.

The max buad rate is set correct to 115200 and i see sometimes the start message "FALCOX OVER DISPLAY PORT" but this message stays and the osd wont get displayed. Most of the times nothing will be displayed.

Then i have flashed BetaFlight and there the OSD works as expected without any issues :/

**Comment by PGIII** [comment]
Sounds like they must have changed something we will have to look into it

**Comment by Tigereye2k6** [comment]
A little update: I have downgraded the SharkByte firmware to the previous version and the OSD works. So there is definitely some issue with the new firmware version and falcox.

**Comment by ligenxxxx** [comment]
Try to disconnect the TX on the VTX side to see if the OSD can be displayed normally.

**Comment by Tigereye2k6** [comment]
I will try it 😉

**Comment by Tigereye2k6** [comment]
Have tried it, but it wot work either :/

**Comment by AzulloCyll** [comment]
OSD not working on H7 Lightning too! Same SB firmware.

**Comment by PGIII** [comment]
Just pushed a new alpha that fixes this issue

**Comment by Tigereye2k6** [comment]
Thank you very much!! ❤️

**Comment by Tigereye2k6** [comment]
Have tried it and i can confirm its fixed!
