### ISSUE TITLE
Newbeedrone infinity target issue finding control link 

### ISSUE THREAD

**Issue by kevinjulieevan** [FlightOne/FalcoX-Issue-Tracker#281]
Newbeedrone infinity target seems to have a bug . Can’t detect radio control link . I tried different tx pads , different rx pads and ghost protocol as well as srxl2 with no detection . Sounds like others with similar issues with this target 
Kevin t 

*Version**
What version are you using, ex. 10.0.6.2804, can be found at boot up or in configurator

**Target**
What target are you using ex. Revolt

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by WildWillyFL1** [comment]
What UARTs did you try?
