### ISSUE TITLE
Target NBDINFINITYF4 Issue Detecting Rx

### ISSUE THREAD

**Issue by PanicoFPV** [FlightOne/FalcoX-Issue-Tracker#283]
The Target NBDINFINITYF4 has a bug that will not allow user to get through the radio wizard. It is not picking up Crossfire (FW 6.09 or 6.10) . Manually updating UART to RX does not work either.

**Comment by WildWillyFL1** [comment]
What UARTs have you tried hooking it up to?

**Comment by PanicoFPV** [comment]
Hi- 

It was UART 3. 

Richard Panico

**Comment by WildWillyFL1** [comment]
Are there any other non-inverted UARTs on that FC you can try hooking it up to test?

**Comment by PanicoFPV** [comment]
Hi Willy- 

I’m not sure to be honest. Looks like UART 1 & 6 are taken by DJI? 



Richard Panico

**Comment by PanicoFPV** [comment]
I don’t know how to tell whether it’s uninverted other than the diagram I just sent. If I need to look for something on the FC that will determine that, just lemme know. 

Richard Panico

**Comment by PanicoFPV** [comment]
Just following up here. Anything I can do to test something out? Please lemme know. 

Richard Panico

**Comment by PanicoFPV** [comment]
Good day- 

Just following up again. Can someone please help a brotha out? 

Richard Panico

**Comment by WildWillyFL1** [comment]
> Good day- Just following up again. Can someone please help a brotha out? Richard Panico
> […](#)
> On Nov 19, 2021, at 8:07 AM, Richard Panico ***@***.***> wrote: ﻿Just following up here. Anything I can do to test something out? Please lemme know. Richard Panico >> On Nov 18, 2021, at 8:45 AM, Richard Panico ***@***.***> wrote: >> > ﻿I don’t know how to tell whether it’s uninverted other than the diagram I just sent. If I need to look for something on the FC that will determine that, just lemme know. > > Richard Panico > >>> On Nov 18, 2021, at 8:43 AM, Richard Panico ***@***.***> wrote: >>> >> ﻿Hi Willy- >> >> I’m not sure to be honest. Looks like UART 1 & 6 are taken by DJI? >> >> <image0.jpeg> >> >> >> Richard Panico >> >>>> On Nov 18, 2021, at 1:28 AM, WildWillyFPV ***@***.***> wrote: >>>> >>> ﻿ >>> Are there any other non-inverted UARTs on that FC you can try hooking it up to test? >>> >>> — >>> You are receiving this because you authored the thread. >>> Reply to this email directly, view it on GitHub, or unsubscribe. >>> Triage notifications on the go with GitHub Mobile for iOS or Android.

Yeah can you try hooking just the crsf tx line to any uninverted tx or rx pad on the FC and try those, it should work on any non-inverted UART

**Comment by PanicoFPV** [comment]
Me again-

I still cannot flash my NBD Infinity 200 FC.  I'm not sure what the issue
is. I'm not seeing where there is an uninverted pad according to NBD's
website (see pic below). Are you saying i need to rewire the RX to get it
to work because in BF & EMU my rx is listed and wired to UART 4. I believe
I mistakenly told you UART 3 in a previous email, my apologies for that.
However, I had been trying UART 4 and that didn't work. Can you please let
me know how I should proceed?



[image: image.png]
