### ISSUE TITLE
Setup Wizard fails to recognize CRSF on Racepit

### ISSUE THREAD

**Issue by oscarkim007** [FlightOne/FalcoX-Issue-Tracker#285]
Flashed a Racepit F4 with FalcoX Alpha latest firm but Setup fails to recognize the CRSF (soldered to the designated tx1,rx1 pad).

**Comment by PGIII** [comment]
Duplicate of #282

**Comment by Fianco182** [comment]
Haii, i have a the same issues, i had a Racepit F4 and try to flash firmware with the falcoX , but now the csfr not detected , i use betafpv elrs 900, in betaflight / emuflight can detected or used, but in falcox cannot detected the csfr, i followed the wiring Tx to RX FC , RX to TX fc, but still not working, but i havent try the inverted flash. 
can u help me guys ? 🥲
