### ISSUE TITLE
Flight controller will not rearm after light crash.  

### ISSUE THREAD

**Issue by shawnames** [FlightOne/FalcoX-Issue-Tracker#29]
**Version**
10.0.6.3065

**Target**
millivolt

**Describe the bug**
Intermittent issue.  After a small crash the quad will not rearm or respond to the command to open the OSD.  OSD values still change and the quad STILL responds to the command for pintoggle which leads me to believe it is not an issue with the rx.  Power cycle fixes the issue.

**To Reproduce**
1. Crash
2. Attempt to arm

**Comment by PGIII** [comment]
If its crash related its unlikely a firmware issue but is it easy to reproduce and have you experienced it on multiple quads ?
