### ISSUE TITLE
iflightf722twing Motor 1 Not Spinning

### ISSUE THREAD

**Issue by bspires123** [FlightOne/FalcoX-Issue-Tracker#290]
**Version**
What version are you using, ex. 10.1.1.5829, can be found at boot up or in configurator

**Target**
What target are you using ex. flx_iflightf722_twing

**Describe the bug**
at configuration when asked if motors are on only 3 motors running (m1 not spinning) with props reversed selected in previous question.
when selected normal props zero motors spin
this is coming from a previous build running BF and all motors run correctly
flashed BF again and all motors run correctly
pinout bug?

**To Reproduce**
described above

**Expected behavior**
1 or no motors spinning

**Screenshots**

**Additional context**

**Comment by PGIII** [comment]
[FLX_IFLIGHTF722_TWING_10.1.1.5842.flx.zip](https://github.com/FlightOne/FalcoX-Issue-Tracker/files/7781382/FLX_IFLIGHTF722_TWING_10.1.1.5842.flx.zip)
Try this and see if it fixes the issue
