### ISSUE TITLE
FalcoX Matek F411  Buzzer out of control

### ISSUE THREAD

**Issue by yi3yi4** [FlightOne/FalcoX-Issue-Tracker#30]
My FC is GEP-20A-F4，Only have 5V and BZ - two pads
Two wire buzzer will work all the time
Buzzer On and Pin Toggle no effect

**Comment by JRTrudel** [comment]
Same Problem with all my AIO board....    Can wee expect a fix?

**Comment by Tonsuke201450** [comment]
Same here.  Any update ?

**Comment by PGIII** [comment]
Try Version 10.1.0.5252 |10.1 Alpha 15| and see if you still have the issue

**Comment by Tonsuke201450** [comment]
It stopped beeping but doesn't beep this time.
