### ISSUE TITLE
Tmotor Pacer F7 could not calibrated gyro when armed

### ISSUE THREAD

**Issue by agmazlan** [FlightOne/FalcoX-Issue-Tracker#303]
**Version**
10.1.1.5901

**Target**
Tmotorpacerf7

**Describe the bug**
gyro cannot calibrated after armed when try to take off the quad fly away like crazy already try the rotation and motor direction all normal
gryo mpu6000

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by PGIII** [comment]
Sounds like something isn't configured correctly, try typing RESETCONFIG in the terminal and then going through the setup process again
