### ISSUE TITLE
Addressable Led not working on mamba dji f722 mini mk2

### ISSUE THREAD

**Issue by signaldown** [FlightOne/FalcoX-Issue-Tracker#308]
Mamba dji f722 mini mk2 (purple board) led not working

firmware version 10.1.1.5956 |10.1 Alpha 49|

I already connect Led in form led strip to Led pad on the fc and select type of led models but still not working, in other firmware (betafl***t) works fine 

please fix this issue,

thanks...

**Comment by PGIII** [comment]
What target is the board flashed with ?

**Comment by signaldown** [comment]
> What target is the board flashed with ?
> 

mamba F7 sir...
