### ISSUE TITLE
Backup / Restore checkbox groups

### ISSUE THREAD

**Issue by Hellfire82** [FlightOne/FalcoX-Issue-Tracker#33]
On the Backup / Restore screen, the checkbox groups are not all visible unless you have the window maximised. There is no scroll bar to adjust this and they seem to be misaligned:

Windowed

![windowed](https://user-images.githubusercontent.com/61711435/81159459-e2b01d80-8f80-11ea-8f18-5d7be0c3cb3b.jpg)

Maximised

![maximised](https://user-images.githubusercontent.com/61711435/81159451-e04dc380-8f80-11ea-8ad1-b123fa4f08c4.jpg)

In addition it would be much easier if there was a 'check / uncheck all' button for these groups, if for example you only wanted to backup OSD.

 - OS: Windows 8.1
 - Browser: Chrome
 - Version: 81.0.4044.138 (Official Build) (64-bit)

**Comment by PGIII** [comment]
What resolution is your monitor ?

**Comment by Hellfire82** [comment]
1366x768 - The highest resolution my laptop will go to.

![laptop screen](https://user-images.githubusercontent.com/61711435/81211671-9d650d80-8fcb-11ea-8078-7cb0014494b7.jpg)
