### ISSUE TITLE
New Configurator VTX Settings (Alpha Test)

### ISSUE THREAD

**Issue by SkeemoFPV** [FlightOne/FalcoX-Issue-Tracker#37]
In the VTX section the protocol and VTX type is just displayed as a number with nothing to reference too. 
Needs to either have a key or the actual names in the dropdown.
This is also the same for the Auto/PAL/NTSC box.

**To Reproduce**
1. Go to 'Configuration'
2. Click on 'VTX'
3. Observe the selection menus

**Expected behaviour**
I would like to see the actual name of the protocols and the cards listed.

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser: Chrome
 - Configurator Version: Version 10.0.4-alpha
![Screenshot 2020-05-08 at 13 32 57](https://user-images.githubusercontent.com/25980738/81406307-3bbeb380-9131-11ea-9d2e-3347917f66c2.png)

**Comment by PGIII** [comment]
I pushed a new firmware a couple days ago that should make the VTX page work properly, and fixes some missing names

**Comment by SkeemoFPV** [comment]
Yes that’s working great now thanks.
