### ISSUE TITLE
no final 2 bip boot (alpha 3622)

### ISSUE THREAD

**Issue by ElMute** [FlightOne/FalcoX-Issue-Tracker#40]
no final bip boot with the 3622 version, can't use it.
tried to DFU flash, but it doesn't work correctly on the new configurator

**Comment by PGIII** [comment]
Havent heard of anyone else having that issue what target, esc, and esc protocol are you using

**Comment by ElMute** [comment]
set-up > revolt OSD lite, Megabolt Extreme, DShot 64 but same issue with DShot 32
i've 2 setup exactly the same, and i got this issue on both

**Comment by PGIII** [comment]
Can you post a dump from the quad in here

**Comment by ElMute** [comment]
> Can you post a dump from the quad in here

here it is 
[ElMute Tune ok.txt](https://github.com/FlightOne/FalcoX-Issue-Tracker/files/4674617/ElMute.Tune.ok.txt)

**Comment by ElMute** [comment]
> Can you post a dump from the quad in here

just to say, the final bips are here just after the flash, if the USB is plugged and connected to the configurator, as soon as i unplugged the FC, final bips are gone, and don't come back even if i replug the USB.
would be glad if you find a way to resolve this bug :)

**Comment by PGIII** [comment]
3625 should resolve this issue
