### ISSUE TITLE
New configurator Test - Cannot upgrade the FW to latest 3373

### ISSUE THREAD

**Issue by cross07705** [FlightOne/FalcoX-Issue-Tracker#46]
When plug in the FC first time, the new configurator detect the latest FW is 3373. But there is no response after clicking update. 
Then unplug and plug in the FC again, the new configurtor change the latest FW back to 3266, and update function works.
Is the new configurator only support 3266?
Thank you.

**Comment by ElMute** [comment]
just flash one of my kwad with 3373 and old configurator, and this firmware don't work with the new alpha configurator. seems only 3266 can work with him

**Comment by PGIII** [comment]
needs to be 10.0.7.x to support the new configurator, therell be a new update to the configurator soon that should fix it showing the wrong version number as the latest

**Comment by ElMute** [comment]
great will try

**Comment by cross07705** [comment]
Noted with thanks!
