### ISSUE TITLE
SIM mode can't be disabled

### ISSUE THREAD

**Issue by ElMute** [FlightOne/FalcoX-Issue-Tracker#47]
x.3065, x.3373, 7,3377
revolt OSD lite

can't disabled SIM mode, he is back to on even after saved

put SIM mode off, switch between profiles, sim mode is back to on
put SIM mode off, unplug FC, replug FC, SIM mode is back to on

**Comment by PGIII** [comment]
Certain features require sim mode like dynamic AA so if youre using something like that itll force it on

**Comment by ElMute** [comment]
ok i use dynamic AA, so it's understood :)
