### ISSUE TITLE
VTX smart Audio Unify Pro32 HV

### ISSUE THREAD

**Issue by michael9544** [FlightOne/FalcoX-Issue-Tracker#48]
10.0.7.3377

Revolt

VTX smart Audio Unify Pro32 HV every time go on max ( 1000mw) when leave OSD whitout  "save and exit"

0. Unify is on e.g 100mv

1. enter OSD
2. leave OSD with "exit"
3. unify then every time change the max (1000mw) after reboot

no problem when leave OSD with "save and exit"

**Comment by PGIII** [comment]
You need to make sure you pick send settings in the VTX menu to set the settings you want

**Comment by michael9544** [comment]
yes, of course I always do that.
the bug has only existed since version 10.0.6.3065.

**Comment by SkeemoFPV** [comment]
This is the same as I was having with Unify Pro32 HV randomly setting itself to 1000mW
