### ISSUE TITLE
Two motors stopped

### ISSUE THREAD

**Issue by SkeemoFPV** [FlightOne/FalcoX-Issue-Tracker#5]
Toothpick with Matek F411 target. NamelessRC AIO412.
JESC 48khz with telemetry enabled
Set up went all fine, first test flight in auto-level was perfect for around 30s then two motors stopped. Tried to re-arm and still only two motors. Everything was ok after a power cycle, then again after about 30s two motors stopped.

**Comment by PGIII** [comment]
Just Posted a new version, try that when you get a chance and let me know if you still have the issue

**Comment by SkeemoFPV** [comment]
Unfortunately that has not fixed it, plus I now in get two motors spinning in the setup. I flashed backed to BF and confirmed everything was working, which it is, then DFU flashed the latest FalcoX, and still only have two motors working. I have tried both JESC 2.2 and 2.3 which made no difference.

**Comment by SkeemoFPV** [comment]
The latest FW 10.0.6.2818 has fixed this problem for me, thank you, awesome work !!!!

**Comment by ujenmr** [comment]
I still have problem on FW FLX_MATEKF411_10.0.6.2999.flx unfortunately falcox is unflyable for me
