### ISSUE TITLE
Falcox Configurator 2.0.2 stuck at save/restore, configure OSD tabs

### ISSUE THREAD

**Issue by VictorWYVan** [FlightOne/FalcoX-Issue-Tracker#50]
**Describe the bug**
Companion is stuck showing 'Loading...' when I click 'Configure OSD' tab or 'Backup/Restore - backup'

Target: Revolt
Version: 10.0.6.3373

**To Reproduce**
1. Go to 'FalcoX Configurator', plug in the quad
2. Click on 'Configure OSD' or 'Backup/Restore'
3. If clicked 'Backup/Restore', click 'backup'

**Expected behavior**
Configurator hangs

**Screenshots**
![image](https://user-images.githubusercontent.com/24494256/83544959-42262c80-a531-11ea-8c19-9fa56e79f22b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Browser chrome
 - Version Windows 10 1903

**Comment by danbritt** [comment]
Also happening for me on MambaF411 target, same FW and configurator version as above.

I did notice that if you open the dev tools using the electron menu, you can see all of the commands being dumped to the console when you click the "backup" button. I can also see the commands being dumped to the console if I go to the terminal tab, type "dump", and then hit enter. So it appears the dump is working, it's just not presenting the user with an option to do anything with it.

**Comment by pajalnic** [comment]
Also happening for me on  revoltOsd target, same FW and configurator version as above.

**Comment by JRTrudel** [comment]
Very annoying bug...

**Comment by PGIII** [comment]
This will be fixed in the upcoming release, the current prealpha configurator doesnt have this issue
