### ISSUE TITLE
Falcox Configurator 2.0.2 - No output shown in terminal when executing commands

### ISSUE THREAD

**Issue by danbritt** [FlightOne/FalcoX-Issue-Tracker#52]
**Describe the bug**
When you execute a command, nothing shows up in the textarea above the command entry to give you any feedback.

**To Reproduce**
1. Go to the "serial terminal" tab
2. Type "dump" in the command box
3. Hit enter
4. Nothing is displayed

**Expected behavior**
Some sort of output from the commands executed should show in the main textarea so the user has some feedback, especially with the dump command.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Windows 10 v1903

**Comment by PGIII** [comment]
This is fixed  in the latest configurator
