### ISSUE TITLE
Settings cannot be changed in Tuning page

### ISSUE THREAD

**Issue by cross07705** [FlightOne/FalcoX-Issue-Tracker#6]
Target: MambaF411
In latest 2796 fw. I found PID numbers and other settings cannot be changed except 'Profile for' option in tuning page. Other pages are fine.

**Comment by PGIII** [comment]
Should be fixed in the latest version just posted, please try that when you get the chance

**Comment by cross07705** [comment]
Tested the latest version, issue is solved. Thank you!
