### ISSUE TITLE
[FEATURE] native Blheli pass through 

### ISSUE THREAD

**Issue by RoninMedia12** [FlightOne/FalcoX-Issue-Tracker#61]
**Is your feature request related to a problem? Please describe.**
Having to flash to BF to Use Blheli config. 

**Describe the solution you'd like**
Native Blheli32 pass through in FalcoX   Or ability to edit more setting in blheli32 in Falcox OSD:  motor timing, Demag, PWM, startup power.  

**Describe alternatives you've considered**
Old flight one method of having Cleanflight firmware flashable easily from the configurator.  

**Additional context**

**Comment by PGIII** [comment]
This is already supported on Lightning

**Comment by RoninMedia12** [comment]
So no support coming for revolt and revolt osd only new lighting board?

**Comment by gretel** [comment]
why is this getting closed? customers asking for this feature. spending more money on another board which will not fit  smaller builds is not an option for me.

**Comment by PGIII** [comment]
@gretel support for all targets was just added, also the lightning is smaller than the millivoltOSD so not sure how it wouldnt fit in a build

**Comment by gretel** [comment]
@PGIII awesome, thank you. will there be an according release at https://flightone.com/download.php?version=alpha ?

**Comment by RoninMedia12** [comment]
Thank very much PG3
