### ISSUE TITLE
Dji fpv rssi still not working with crsf it just shows 9

### ISSUE THREAD

**Issue by rosspeterson1** [FlightOne/FalcoX-Issue-Tracker#69]
**Version**
What version are you using, ex. 10.0.6.2804, can be found at boot up or in configurator

**Target**
What target are you using ex. Revolt

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by PGIII** [comment]
This is being looked into likely a conversion issue

**Comment by RoninMedia12** [comment]
having same issue do we need to setup channel output on xfire rx at all?

**Comment by PGIII** [comment]
> having same issue do we need to setup channel output on xfire rx at all?

Yes it needs to output LQ on channel 8 for the FC to see the data
