### ISSUE TITLE
Issues flashing Revolt V2

### ISSUE THREAD

**Issue by KrickeH** [FlightOne/FalcoX-Issue-Tracker#7]
**Version**
10.0.6.2804

**Target**
Revolt V2

**Describe the bug**
Can't load firmware on the board.

"Update to latest version" button loads Target: Bnf_mambaf411, Version: 1.0.0.2796 and Configurator just search for flight controller endlessly after that (Pic_1).

"Flash manually with file"  button (using FLX_REVOLT_10.0.6.2804.flx) stops on Loading blinking but never countinues to load the firmware ( waited over 15 minutes just to be sure) (Pic_2).

Flashing FLX_REVOLT_10.0.5.2527.flx manually works as it should (Pic_3)

**To Reproduce**
Happens everytime using normal firmware update procedures.

**Expected behavior**
Get Target: Revolt Version: 10.0.6.2804 working on the board :)

**Screenshots**

![pic_1](https://user-images.githubusercontent.com/29928367/75636048-a0cec800-5c1b-11ea-8017-88df9592f870.png)
![pic_2](https://user-images.githubusercontent.com/29928367/75636049-a1675e80-5c1b-11ea-8639-8d2c4909f653.png)
![pic_3](https://user-images.githubusercontent.com/29928367/75636050-a1675e80-5c1b-11ea-8871-1cd229b60960.png)

**Desktop**

- OS: Windows 10 pro 1909 18363.693
 - Browser: Microsoft Edge 80.0.361.62

**Comment by PGIII** [comment]
That sounds like you have the wrong bootloader version, can you go into dfu mode and get the serial number of the board, has the board had its MCU replaced in the past ?

**Comment by KrickeH** [comment]
Serial Number: 3085395F3235

And nothing is replaced / changed.

**Comment by PGIII** [comment]
try updating through DFU mode now

**Comment by KrickeH** [comment]
Working as it should now..

Excellent!
