### ISSUE TITLE
no data shown on the OSD emulator

### ISSUE THREAD

**Issue by ElMute** [FlightOne/FalcoX-Issue-Tracker#71]
no data shown on the OSD emulator

**To Reproduce**
launch congurator
plug the H7
H7 is detected
no information shown on the OSD emulator

https://zupimages.net/viewer.php?id=20/47/3jkl.png

MAC OS 10,14,16

**Comment by PGIII** [comment]
The Mac version of the configurator is having some issues were looking into it
