### ISSUE TITLE
can't enter in OSD with stick down and left

### ISSUE THREAD

**Issue by ElMute** [FlightOne/FalcoX-Issue-Tracker#72]
15,46,47

H7

can't enter in the OSD, put stick down and left but no reaction

**To Reproduce**
plug the H7 to your computer
H7 is detected
but stick down left not enter in the OSD

**Comment by PGIII** [comment]
Havent heard of anyone having this issue have you tried resetting wizard and going through them again

**Comment by ElMute** [comment]
Hey PGIII, sorry didn,'t update it, but you can close this issue, it's link to the MAC Catalina issues with the configurator, and freeze of the OSD emulator
