### ISSUE TITLE
configurator 10.0.12 stuck on Loading MAC OS Mojave

### ISSUE THREAD

**Issue by ElMute** [FlightOne/FalcoX-Issue-Tracker#73]
configurator 10.0.12

Configurator stuck on Loading
OSD Emulator shows nothing

click on tuning or configuration tab, see it's stuck on Loading

MAC OS Mojave 10.14.6
 - chrome

all is working under windows 10 on the same computer with bootcamp

**Comment by PGIII** [comment]
Closing since this falls under #77
