### ISSUE TITLE
Revoltosd, OSD Font " Mega"

### ISSUE THREAD

**Issue by michael9544** [FlightOne/FalcoX-Issue-Tracker#75]
10.0.16.4680 

RevoltOSD

OSD Font, "Mega" not working

if DFU Flash 10.0.16.4680 the OSD Font"Mega" is not Working

if previously an older version, e.g. 10.0.6.3923 was installed, and then update to 10.0.16.4680  the osd works correctly

**Comment by PGIII** [comment]
Hmm thats very odd ill have to test, does flashing normally through bootloader after DFU flashing work fine ?
