### ISSUE TITLE
BLheli Telemetry Cancellation Failing

### ISSUE THREAD

**Issue by Rafyel** [FlightOne/FalcoX-Issue-Tracker#8]
I have blheli32 ESC’s but when I enter the detection wizard it doesn’t find anything and I cannot cancel the detection using the sticks. I have to unplug the battery to get out of the menu.

**Comment by ElMute** [comment]
same here :)

**Comment by PGIII** [comment]
Is the blue light still blinking when it happens?

**Comment by ElMute** [comment]
Yes, still blinking

**Comment by PGIII** [comment]
Just pushed a new version to the site that fixes the issue
