### ISSUE TITLE
v10.0.13  Backup only saves profile 1 if using multiple profiles their settings never get saved

### ISSUE THREAD

**Issue by Rickcau** [FlightOne/FalcoX-Issue-Tracker#80]
Problem Description:
Open config version 10.0.12 and change to profile 2 and make some changes and save them, then backup those settings to disk.  The backup file does not have the profile 2 settings, only profile 1.

**To Reproduce**
1. Open config version 10.0.12 and change to profile 2 and make some changes and save
2. Now click the Backup/Restore to save your settings to disk
3. The the text file that it just crated and you will see it has profile 1 settings

This results in a situation in-which you cannot save your profile to settings to disk.  The only work around is to go into terminal and issue dump command and copy those settings to a file.

The code base should allow you to save all settings for all profiles and at a minimum when backup is clicked it should save the currently selected profile to disk.
 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by PGIII** [comment]
Can you upload the file it created ?
