### ISSUE TITLE
No BLHeli passthrough in Alpha 4984

### ISSUE THREAD

**Issue by ElMute** [FlightOne/FalcoX-Issue-Tracker#90]
Lightning Alpha 4984

Impossible to connect BLHeli32

just intall Stable release  4939 and all is working great with BlHeli32

**Comment by rosspeterson1** [comment]
Not working on mine either for the  h7 , revoltosd, or revolt

**Comment by PGIII** [comment]
will look into it this week

**Comment by PGIII** [comment]
try 10.1.0.5135, should fix this
