### ISSUE TITLE
OmniBusF4 - Issues spinning motors with Blheli_s ESC

### ISSUE THREAD

**Issue by svoland** [FlightOne/FalcoX-Issue-Tracker#94]
**Version**
10.1.0.5043

**Target**
omnibusf4sd - lanrc f4 v3s

**Describe the bug**
motor setup wont end - motor wont spin at any idle %

**To Reproduce**
1. start setup proccess
2. go to motor spin test

**Expected behavior**
the motor should start spinning at some idle %

**Screenshots**

**Additional context**

**Comment by PGIII** [comment]
I cant find much info on the board its for sure a omnibusf4sd target ? also what esc are you using ?

**Comment by svoland** [comment]
> I cant find much info on the board its for sure a omnibusf4sd target ? also what esc are you using ? 

I used lanrc stack, link below. It's came with this target and works with BF fine


https://www.joom.com/en/products/5fbcc3768248510107c8c3e7

**Comment by PGIII** [comment]
Try 10.1.0.5135 should fix issues with blheli_s escs not spinning

**Comment by svoland** [comment]
> Try 10.1.0.5135 should fix issues with blheli_s escs not spinning

Fixed
