### ISSUE TITLE
omnibusf4sd  - Issue Detecting Iflight VTX

### ISSUE THREAD

**Issue by svoland** [FlightOne/FalcoX-Issue-Tracker#95]
**Version**
10.1.0.5043

**Target**
omnibusf4sd - lanrc f4 v3s
VTX - iFlight succex force - uses irc trump protocol

**Describe the bug**
on the initial setup, wont find any vtx connected ( the same setup works with betaflight )

**To Reproduce**
1. start fc config 
2. wont fount any vtx

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by PGIII** [comment]
Try 10.1.0.5135 and see if you still have the issue

**Comment by svoland** [comment]
> Try 10.1.0.5135 and see if you still have the issue

Still have the issue. 
VTX connected to tx3.

**Comment by svoland** [comment]
The manual selection works fine for SA and irc Tramp. The auto detect won't work for both, for different TX on the board

**Comment by PGIII** [comment]
What do you mean Manual works for SA and Tramp, doesnt that VTX only use the tramp protocol ?

**Comment by svoland** [comment]
> What do you mean Manual works for SA and Tramp, doesnt that VTX only use the tramp protocol ? 

Sorry,
Tested it with iFlight VTX ( irc Tramp) and with rushtank VTX ( SA 2.0 ). On 2 different uarts. Same results - auto detect didn't worked for both. Manual configuration worked well for both
