### ISSUE TITLE
Jhemcu GHF420AIO F4 Esc Doesnt boot

### ISSUE THREAD

**Issue by eduenlamer** [FlightOne/FalcoX-Issue-Tracker#98]
Version: 10.1.0.5142

Target: BETAFLIGHTF4

Describe the bug
Esc doesn't boot when applying power. Setup works until I get to the motor part.

1. Flash BETAFLIGHTF4 Target
2. Initiate setup
3. Setup works until the motor part. 
4. No matter how much I increase the idle % the motors doesn't spin.

Expected behavior:
The motors should start spinning

Additional context:
Problem doesn't exist on with betaflight flashed to it.

**Comment by PGIII** [comment]
Try 5164 and see what it does
